services:

  db:
    image: postgres:17-alpine
    container_name: ippo_db
    environment:
      POSTGRES_DB: ippo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ippo_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: ippo_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ippo_db
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    ports:
      - "8080:8080"

volumes:
  postgres_data:
